### ISSUE TITLE
Autosplitter settings reset on each update

### ISSUE THREAD

**Issue by MrSir71** [DevinR528/bo_autosplitter#4]
Whenever a new update gets pushed for the autosplitter, it resets all of the split points to your any% default, which at the moment is not what I use. Maybe we could get an export file of some kind to save our settings? I think for other games I've seen this data saved in the .lss file somehow, not store in the autosplitter itself.

**Comment by MrSir71** [comment]
New data: Livesplit must be reset everytime you reset a run now, since it will not split a split ever again in a given instance of livesplit once it has done so once. This would be alright, but combined with the above it does become a much bigger problem. Some way of preserving the settings will need to be found to accommodate runners with different split preferences.

**Comment by DevinR528** [comment]
After talking with the LiveSplit people turns out this is a solved problem and I just need to read the splits file and update the settings Map provided by the AutoSplitter runtime. 

This was 2 commits - 
https://github.com/DevinR528/bo_autosplitter/commit/9779a137ec360e5a10f871da51e63e39b240eafc
https://github.com/DevinR528/bo_autosplitter/commit/a61154bf87b5cd38e192bf861f272fcd26044175

**Comment by DevinR528** [comment]
Going to close this as fixed if there are any issues feel free to reopen!
